-- Inserción de datos

-- 10 Registros de Conductor
INSERT INTO Conductor (nombre_conductor) VALUES
('Juan Perez Fernandez'),
('Gabriel Garcia Lopez'),
('Maria Cueva de las Nieves'),
('Jorge Vilca Huaman'),
('Joaquin Pinzon Achata'),
('Martin Castillo Ramos'),
('Andre Ventura Gallegos'),
('Piero Hector Durand Diaz'),
('Erick Paricahua Bautista'),
('Sergio Ivan Salazar Luque');

-- 24 Registros de Modelo
INSERT INTO Modelo (modelo_descripcion) VALUES
('S3P'),
('HFC1061KC'),
('HFC1030KL'),
('HD-65'),
('GD (SERIE 500)'),
('FL611(4X2)'),
('FL10'),
('FL-7'),
('FH12 8X2'),
('FE 6X2 R'),
('FD (SERIE 500)'),
('FC(SERIE 500)'),
('F10'),
('DUTRO (SERIE 300)'),
('DAMAS'),
('CL 120'),
('BJ1226VMPHN-AA'),
('AN64TX'),
('ACTROS 2645 LS'),
('9200I SBA 6X4'),
('7600 SBA 6X4'),
('3S'),
('3-S'),
('206C');

-- 50 Registros por Ruta
INSERT INTO Ruta (kilometraje, descripcion, tipo_ruta, estado_ruta) VALUES
(900, 'AREQUIPA - TACNA', 'Local', 0),
(780, 'AREQUIPA - SICUANI', 'Provincial', 0),
(910, 'AREQUIPA - SANTO TOMAS', 'Provincial', 1),
(490, 'AREQUIPA - ILO', 'Provincial', 0),
(840, 'AREQUIPA - JULIACA - AZANGARO - AYAVIRI', 'Provincial', 1),
(400, 'AREQUIPA LOCAL', 'Local', 1),
(500, 'AREQUIPA - MOQUEGUA', 'Provincial', 1),
(749, 'AREQUIPA -JULIACA - PUNO -ILAVE', 'Provincial', 1),
(290, 'AREQUIPA - PEDREGAL', 'Provincial', 1),
(430, 'AREQUIPA - CAMANA', 'Provincial', 1),
(350, 'AREQUIPA - COCACHACRA - MOLLENDO', 'Provincial', 1),
(620, 'AREQUIPA - ESPINAR', 'Provincial', 1),
(1180, 'AREQUIPA - CUSCO - URUBAMBA', 'Provincial', 0),
(544, 'AREQUIPA - JULIACA', 'Provincial', 1),
(195, 'AREQUIPA - LA JOYA', 'Provincial', 1),
(860, 'AREQUIPA - TOMASIRI - TACNA', 'Provincial', 0),
(690, 'AREQUIPA - JULIACA - AYAVIRI - HUANCANE', 'Provincial', 1),
(1120, 'AREQUIPA - CUSCO', 'Provincial', 1),
(733, 'AREQUIPA - JULIACA - PUNO', 'Provincial', 1),
(625, 'AREQUIPA - ILO - MOQUEGUA', 'Provincial', 0),
(401, 'AREQUIPA- CORIRE - APLAO', 'Provincial', 1),
(0, 'AREQUIPA-JULIACA-AZANGARO', 'Provincial', 1),
(243, 'AREQUIPA - LA JOYA - SAN ISIDRO- LA CANO - SANTA R', 'Provincial', 1),
(830, 'AREQUIPA - ATICO - CHALA', 'Provincial', 1),
(500, 'AREQUIPA - COCACHARA - MOLLENDO - CAMANA', 'Provincial', 1),
(710, 'AREQUIPA - JULIACA - HUANCANE', 'Provincial', 1),
(1, 'VITOR - SANTA RITA - PEDREGAL', 'Provincial', 0),
(725, 'AREQUIPA - MAÑAZO - PUNO - ILAVE', 'Provincial', 1),
(348, 'AREQUIPA JULIACA AYAVIRI', 'Provincial', 1),
(1, 'AREQUIPA-PUNO-ILAVE-JULY-DESAGUADERO', 'Provincial', 1),
(960, 'AREQUIPA- MAÑAZO- PUNO- ILAVE - DESAGUADERO', 'Provincial', 1),
(630, 'AREQUIPA - MAÑAZO - PUNO', 'Provincial', 1),
(900, 'AREQUIPA - PUNO - YUNGUYO - DESAGUADERO', 'Provincial', 1),
(700, 'AREQUIPA-ILAVE-JULI', 'Provincial', 1),
(1057, 'AREQUIPA-SAN ANTON-MACUSANI-OLLACHEA', 'Provincial', 1),
(725, 'AREQUIPA - PUNO - ILAVE (USAR OPERACION MAÑAZO)', 'Provincial', 0),
(1120, 'AREQUIPA - SICUANI - CUSCO', 'Provincial', 0),
(1540, 'AREQUIPA - JULIACA - LA PAMPA', 'Provincial', 0),
(1520, 'AREQUIPA - LA PAMPA', 'Provincial', 0),
(200, 'MOQUEGUA LOCAL', 'Local', 1),
(210, 'MOQUEGUA - ILO', 'Provincial', 1),
(175, 'CUSCO (OROPESA) - URUBAMBA', 'Provincial', 1),
(400, 'CUSCO - LOCAL', 'Local', 1),
(132, 'CUSCO(OROPESA) - ANTA', 'Provincial', 1),
(141, 'CUSCO(OROPESA) - CALCA', 'Provincial', 1),
(266, 'CUSCO(OROPESA) - SICUANI', 'Provincial', 1),
(196, 'CUSCO(OROPESA) - OCONGATE', 'Local', 1),
(352, 'MOQUEGUA - TACNA', 'Provincial', 1),
(950, 'CUSCO (OROPESA) - PUERTO MALDONADO', 'Provincial', 1),
(781, 'CUSCO (OROPESA) - LA PAMPA', 'Provincial', 1),
(2040, 'AREQUIPA - LIMA', 'Provincial', 1);

-- 6 Registros por Vehículo
INSERT INTO Vehiculo (placa, id_conductor, id_modelo, marca, tonelaje, centro_costos) VALUES
('V0H-156', 1, 1, 'Toyota', 5, 'FEMACO Via'),
('V6F-789', 2, 2, 'Volvo', 8, 'FEMACO Garcilazo'),
('V6S-486', 3, 3, 'Hyundai', 7, 'FEMACO Huanuco'),
('V7O-159', 4, 4, 'Hyundai', 8, 'FEMACO Via'),
('V6E-357', 5, 5, 'Hyundai', 9, 'FEMACO Garcilazo'),
('V3F-123', 6, 6, 'Toyota', 10, 'FEMACO Huanuco');

-- 15 Registros por Detalle
INSERT INTO Detalle (id_ruta, id_modelo, consumo_por_modelo) VALUES
(1, 1, 12.51),
(2, 2, 14.23),
(3, 3, 10.89),
(4, 4, 37.92),
(5, 5, 16.22),
(6, 6, 15.16),
(7, 7, 16.47),
(8, 8, 17.18),
(9, 9, 13.12),
(10, 10, 16.42),
(11, 11, 9.56),
(12, 12, 15.16),
(13, 13, 16.17),
(14, 14, 16.14),
(15, 15, 12.15);
